on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: 'ubuntu-18.04'
    name: Original HTML Template
    steps:
      - uses: actions/checkout@v2
      - name: Checkout
        run: |
          yarn
      - name: build
        run: |
          yarn build
