on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    runs-on: 'ubuntu-18.04'
    name: build
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn build
